FROM anapsix/alpine-java:8

MAINTAINER alvaro.pozo.cuenca@gmail.com

WORKDIR /home

ADD /compplexGrettings-jar-with-dependencies.jar /home

CMD java -jar compplexGrettings-jar-with-dependencies.jar

EXPOSE 8081 8081
