FROM anapsix/alpine-java:8

MAINTAINER alvaro.pozo.cuenca@gmail.com

WORKDIR /home

ADD /simpleGrettings-jar-with-dependencies.jar /home

CMD java -jar simpleGrettings-jar-with-dependencies.jar

EXPOSE 8080 8080
